version: 2

jobs:
    build:
        working_directory: ~/build
        docker:
            - image: cimg/node:12.22.10
        steps:
            - checkout
            - run: yarn install
            - run: yarn test

workflows:
    version: 2
    development:
        jobs:
            - build:
                context: partner